//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace MP.CrossCutting.Utils.Resources
{
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }

        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MP.CrossCutting.Utils.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu algum problema com a solicitação..
        /// </summary>
        public static string DefaultProblemDetailsTitle
        {
            get
            {
                return ResourceManager.GetString("DefaultProblemDetailsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} já existente..
        /// </summary>
        public static string InvalidEntityAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("InvalidEntityAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} deve ser menor ou igual a {1} caracteres..
        /// </summary>
        public static string InvalidFieldMaxCharsLenght
        {
            get
            {
                return ResourceManager.GetString("InvalidFieldMaxCharsLenght", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O {0} deve ser maior que {1}..
        /// </summary>
        public static string InvalidFieldMinValue
        {
            get
            {
                return ResourceManager.GetString("InvalidFieldMinValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} inválido. Valor nulo ou vazio..
        /// </summary>
        public static string InvalidFieldNullOrEmpty
        {
            get
            {
                return ResourceManager.GetString("InvalidFieldNullOrEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador único inválido..
        /// </summary>
        public static string InvalidID
        {
            get
            {
                return ResourceManager.GetString("InvalidID", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} inválido. Deve ser um número válido..
        /// </summary>
        public static string InvalidNumberField
        {
            get
            {
                return ResourceManager.GetString("InvalidNumberField", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token de acesso inválido ou expirado.
        /// </summary>
        public static string InvalidOrExpiredAccessToken
        {
            get
            {
                return ResourceManager.GetString("InvalidOrExpiredAccessToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um registro com a mesmo valor no campo {0}, mas essa informação deve ser única..
        /// </summary>
        public static string InvalidUniqueValue
        {
            get
            {
                return ResourceManager.GetString("InvalidUniqueValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor {0} não pode ser convertido no enum {1}..
        /// </summary>
        public static string MessageFailEnumConvert
        {
            get
            {
                return ResourceManager.GetString("MessageFailEnumConvert", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não encontrado..
        /// </summary>
        public static string NotFound
        {
            get
            {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu algum problema com os campos da solicitação..
        /// </summary>
        public static string ProblemDetailsDetail
        {
            get
            {
                return ResourceManager.GetString("ProblemDetailsDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreram um ou mais erros de validação..
        /// </summary>
        public static string ProblemDetailsTitle
        {
            get
            {
                return ResourceManager.GetString("ProblemDetailsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não autorizado..
        /// </summary>
        public static string Unauthorized
        {
            get
            {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
